### ISSUE TITLE
Version does not always persist

### ISSUE THREAD

**Issue by ipopescu** [casper-devrel/docs-redux-old#17]
### Category

Error

### Your email address

iulia@casperlabs.io

### Description

The version does not persist when I navigate among the top-level links in the header.
For example, if I choose version "Next", and go from "Developers" to "Operators", the version reverts to 1.5.6. This does not happen if I navigate from a Developers subtopic, such as "Developers Prerequisites" to another subtopic, such as "Building dApps".

### Attachments (optional)

https://github.com/user-attachments/assets/3541902f-fc58-41b4-8ec2-cedf75c03f60

**Comment by melpadden** [comment]
Thanks for this Iulia. We definitely need to find out why this is happening.
